### PR TITLE
align admin buttons on the same line

### PR DESCRIPTION
**Pull request by skeie**
What u think @henrikgs aka itercagemaster aka tha man aka ...

image

### CODE REVIEW

**Comment by henrikgs** [comment]
Sure. What about coloring? Maybe like this:

image

**Comment by henrikgs** [comment]
Or like this:

image

**Comment by skeie** [comment]
Raveparty

image

**Comment by skeie** [comment]
why mæn, WHY?!!

image

**Comment by henrikgs** [comment]
Looooool! Thought this was only an issue – not a PR :P Fix is deploying to production as we speak.. sry

**Comment by skeie** [comment]
I WANT TO BE A CONTRIBUTOOOOOOOOOR
I HATE OPEN SOURCE!!!!!

**Comment by henrikgs** [comment]
sryyyyyyyyyy :-( :-( :-( :-( :-( :-( :-( :-( :-( :-(

**Pull request closed without merging**
